Repository meshery/meshery-osm, pull requests merged in 2022-10, with the labels that each got.

#180 Upgrade to Go 1.19
  .github/workflows/build-and-release.yml
  .github/workflows/ci.yml
  .github/workflows/e2etest.yaml
  .github/workflows/error-ref-publisher.yaml
  .github/workflows/label-commenter.yml
  .github/workflows/update-oam-defs.yml
  .golangci.yml
  Dockerfile
  Makefile
  build/Makefile.core.mk
  build/config.go
  go.mod
  go.sum
  internal/config/config.go
  internal/config/operations.go
  main.go
  osm/error.go
  osm/install.go
  osm/oam.go
  osm/osm.go
  templates/osm-bookstore-traffic-access-v1.yaml
Labels: kind/enhancement, language/go

#189 [CI] go pkg upgrades
  go.mod
  go.sum
Labels: area/ci, language/go

#190 updated multiplatformworkflow git version and commitsha
  .github/workflows/multi-platform.yml
Labels: area/ci, hacktoberfest

#198 Resolve CVE
  go.mod
  go.sum
Labels: security
